site_name: Seagull Docs

site_url: /
use_absolute_urls: true
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/tobegit3hub/seagull
site_description: Seagull docs.
copyright: Copyright &copy; 2015, <a href="https://github.com/tobegit3hub/seagull">Seagull</a>.

docs_dir: en
#docs_dir: zh

#include_search: true
#theme: readthedocs

pages:

# Home
- ['index.md', 'Home']

# User Guide
- ['user_guide/similar-docker-projects.md', 'User Guide', 'Similar Docker Projects']
- ['user_guide/seagull-containers-page.md', 'User Guide', 'Seagull Container Page']
- ['user_guide/seagull-images-page.md', 'User Guide', 'Seagull Images Page']
- ['user_guide/seagull-configuration-page.md', 'User Guide', 'Seagull Configuration Page']
- ['user_guide/seagull-dockerhub-page.md', 'User Guide', 'Seagull DockerHub Page']

# Development
- ['development/access-docker-remote-api.md', 'Development', 'Access Docker Remote API']
- ['development/seagull-design-and-implement.md', 'Development', 'Seagull Design And Implement']
- ['development/implement-i18n-with-angular-translate.md', 'Development', 'Implement I18n With Angular Translate']
- ['development/write-seagull-dockerfile.md', 'Development', 'Write Seagull Dockerfile']
- ['development/use-godep-to-manage-dependency.md', 'Development', 'Use Godep To Manage Dependency']
- ['development/implement-search-with-angular.md', 'Development', 'Implement Search With Angular']
- ['development/use-beego-as-web-server.md', 'Development', 'Use Beego As Web Server']
- ['development/use-beego-as-api-server.md', 'Development', 'Use Beego As API Server']
- ['development/use-angularjs.md', 'Development', 'Use AngularJS']
- ['development/use-bower-to-manage-dependency.md', 'Development', 'Use Bower To Manage Dependency']
- ['development/how-seagull-use-bootstrap.md', 'Development', 'How Seagull Use Bootstrap']
- ['development/use-jquerygritter-for-notification.md', 'Development', 'Use JQuery.Gritter For Notification']
- ['development/implement-angular-filter.md', 'Development', 'Implement Angular Filter']
- ['development/use-animate-css.md', 'Development', 'Use Animate.css']
- ['development/use-drone-for-ci.md', 'Development', 'Use Drone For CI']
